# coda-export/.github/workflows/export-coda-markdown.yml
name: Export Coda Document to Markdown

on:
  workflow_call:
    inputs:
      docID:
        required: true
        type: string
    secrets:
      CODA_API_KEY:
        required: true

jobs:
  export-coda-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout export-coda-markdown repository
        uses: actions/checkout@v3
        with:
          repository: wgu-programs/coda-export
          ref: main

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20' # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run exportCodaToMarkdown script
        run: node --experimental-modules ./scripts/exportCodaToMarkdown.mjs
        env:
          CODA_API_KEY: ${{ secrets.CODA_API_KEY }}
          DOC_ID: ${{ inputs.docID }}
