name: Export Coda Document to Markdown

on:
  workflow_call:
    inputs:
      docID:
        required: true
        type: string
    secrets:
      CODA_API_KEY:
        required: true

jobs:
  export-coda-markdown:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Log current directory
        run: pwd

      - name: List files in the current directory
        run: ls -al

      - name: List files in the scripts directory
        run: ls -al ./scripts

      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: '16' # Specify the Node.js version you need

      - name: Install dependencies
        run: npm install

      - name: Run exportCodaToMarkdown script
        run: node --experimental-modules ./scripts/exportCodaToMarkdown.mjs
        env:
          CODA_API_KEY: ${{ secrets.CODA_API_KEY }}
          DOC_ID: ${{ inputs.docID }}
